### PR TITLE
Delete ITEAM-Prize-Competition-Rules-Document.pdf

### PR DESCRIPTION
**Pull request by ebeidel**
## Preview Links
[Home](addPreviewBranchLinkHere)

[Challenge Page](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/challenges-and-prizes/update-90-iteam-with-new-rules-document-for/challenge/individuals-taking-energy-action-in-manufacturing-iteam/)

## Completion Checklist

- filename starts with the challenge ID #  example-->(1052-challenge-title.md)

- images/docs have been added to the appropriate [assets](https://github.com/GSA/challenges-and-prizes/tree/master/assets) folder

- add alt tags to images in the challenge content body

- test all content links

- test skip links

- add @greensteph as a reviewer when you are ready to go Live

----

>To Note: you cannot use colons in the front-matter data fields

### CODE REVIEW

**Comment by greensteph** [comment]
@ebeidel Is this document referenced in the challenge content anywhere?

**Comment by ebeidel** [comment]
> @ebeidel Is this document referenced in the challenge content anywhere?

@greensteph yes, under Rules - i deleted the old one and uploaded the new one they just sent us.

**Comment by greensteph** [comment]
@ebeidel the link under Rules is an external facing url --> [https://americanmadechallenges.org/iteam/ITEAM_Prize_Competition_Rules.pdf](https://americanmadechallenges.org/iteam/ITEAM_Prize_Competition_Rules.pdf)

**Comment by ebeidel** [comment]
> > @ebeidel Is this document referenced in the challenge content anywhere?
> 
> @greensteph yes, under Rules - i deleted the old one and uploaded the new one they just sent us.



> @ebeidel the link under Rules is an external facing url --> https://americanmadechallenges.org/iteam/ITEAM_Prize_Competition_Rules.pdf

@greensteph You are right. Now, I am not sure then why they sent an updated rules document to us. I'm guessing that, initially, maybe we were pointing to the file as uploaded on our site. And then when this team switched to a new hosting platform, we changed to point out to the rules document on their new site. @twgsa16 - is that right? I think you worked with this team to get them moved over to that new site.

**Comment by ebeidel** [comment]
> > > @ebeidel Is this document referenced in the challenge content anywhere?
> > 
> > 
> > @greensteph yes, under Rules - i deleted the old one and uploaded the new one they just sent us.
> 
> > @ebeidel the link under Rules is an external facing url --> https://americanmadechallenges.org/iteam/ITEAM_Prize_Competition_Rules.pdf
> 
> @greensteph You are right. Now, I am not sure then why they sent an updated rules document to us. I'm guessing that, initially, maybe we were pointing to the file as uploaded on our site. And then when this team switched to a new hosting platform, we changed to point out to the rules document on their new site. @twgsa16 - is that right? I think you worked with this team to get them moved over to that new site.

@greensteph I checked with the agency and told them we're already linking to the rules doc on their site. They said we're good to go then. We should still probably just go through with this pull request, even if it's not changing anything on the front end -- just so we have the most up to date rules doc in our system in case we ever do need reference from our site. Does that make sense?

**Comment by greensteph** [comment]
@ebeidel Sure, sounds good.

**Pull request merged**
